version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"  # Ajusta el puerto según tu aplicación
    command: ["python", "index.py"]